### PR TITLE
Fix for validatorless bootstrap.

### LINKED ISSUE #486: Validatorless boostrap fails with error for knife azurerem server create.
# Version:
[1.8.0]

# Environment: 

It will get reproduced on any OS. I am working on Ubuntu 16.04

# Scenario:

knife azurerm server create command fails with error

```
ERROR: no implicit conversion of nil into String
```

# Steps to Reproduce:
Remove validation_key from knife.rb and from its folder
Run following command 

knife azurerm server create -N vj-chef-test --azure-vm-name vj-chef-test --azure-resource-group-name vj-chef-test --azure-image-os-type windows -x "xxxxx" -P "xxxx" -r "role[windows]"  --azure-service-location westus -c ~/workspace/chef-repo/.chef/knife.rb -VV

# Expected Result:
Validatorless bootstrap for knife azurerm server create should work without any errors.

# Actual Result:
```
ERROR: no implicit conversion of nil into String
ERROR: Something went wrong. Please use -VV option for more details.
DEBUG: /home/msys/.chefdk/gem/ruby/2.5.0/gems/knife-azure-1.8.0/lib/chef/knife/bootstrap/bootstrapper.rb:352:in `read'
/home/msys/.chefdk/gem/ruby/2.5.0/gems/knife-azure-1.8.0/lib/chef/knife/bootstrap/bootstrapper.rb:352:in `get_chef_extension_private_params'
/home/msys/.chefdk/gem/ruby/2.5.0/gems/knife-azure-1.8.0/lib/chef/knife/azurerm_server_create.rb:260:in `create_server_def'
/home/msys/.chefdk/gem/ruby/2.5.0/gems/knife-azure-1.8.0/lib/chef/knife/azurerm_server_create.rb:209:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife.rb:442:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife.rb:441:in `run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife.rb:220:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application/knife.rb:161:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/bin/knife:24:in `<top (required)>'
/opt/chefdk/embedded/bin/knife:23:in `load'
/opt/chefdk/embedded/bin/knife:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by Vasu1105**
### Description
This Fixes validatorless bootstrap error on knife azurerm server create command.

### Issues Resolved

Fixes #486 

### Check List

- [ ] New functionality includes tests
- [x] All tests pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

Signed-off-by: Vasu1105 <vasundhara.jagdale@msystechnologies.com>

### CODE REVIEW

File: lib/chef/knife/bootstrap/bootstrapper.rb [hunk 1]
```diff
@@ -348,8 +350,6 @@ def get_chef_extension_private_params
               key_path = create_node_and_client_pem
               pri_config[:client_pem] = File.read(key_path)
```
Comment (stuartpreston) [inline lib/chef/knife/bootstrap/bootstrapper.rb]: As we now fall through to using the Client pem I think we should also check the client_pem exists and put out a message if we can't find either key.  This would help debugging.

Comment (Vasu1105) [reply lib/chef/knife/bootstrap/bootstrapper.rb]: @stuartpreston  this line of code itself throws and error before we assign that 
```
ERROR: I cannot read /home/msys/workspace/chef-repo/.chef/client.pem, which you told me to use to sign requests!
````
https://github.com/chef/knife-azure/blob/7b7029b0dcf07530e85c626465f297ef6176163e/lib/chef/knife/bootstrap/bootstrapper.rb#L326

so we don't require to validate again. Let me know your thoughts.

Comment (Vasu1105) [reply lib/chef/knife/bootstrap/bootstrapper.rb]: @stuartpreston yes but we can have additional check for if the client.pen generated by client_builder exist on the given path (which is a key_path here). Updated the same. Thank you.

File: lib/chef/knife/bootstrap/bootstrapper.rb [hunk 2]
```diff
@@ -331,7 +331,9 @@ def get_chef_extension_private_params
           pri_config = Hash.new
 
           # validator less bootstrap support for bootstrap protocol cloud-api
-          if (Chef::Config[:validation_key] && !File.exist?(File.expand_path(Chef::Config[:validation_key])))
+          if Chef::Config[:validation_key] && File.exist?(File.expand_path(Chef::Config[:validation_key]))
+            pri_config[:validation_key] = File.read(Chef::Config[:validation_key])
```
Comment (btm) [inline lib/chef/knife/bootstrap/bootstrapper.rb]: I think we should `File.read(File.expand_path("Chef::Config[:validation_key]))` here. Otherwise there's a bug where if `Chef::Config[:validation_key]` is `~/.chef/something.pem` then `File.exist?` will return true but `File.read` would raise `Errno::ENOENT`.

```
2.5.1 :001 > File.exist?("~/home.openvpn.conf")
 => false 
2.5.1 :002 > File.exist?(File.expand_path("~/home.openvpn.conf"))
 => true 
2.5.1 :003 > File.read("~/home.openvpn.conf")
Traceback (most recent call last):
        3: from /home/btm/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        2: from (irb):3
        1: from (irb):3:in `read'
Errno::ENOENT (No such file or directory @ rb_sysopen - ~/home.openvpn.conf)
2.5.1 :004 > File.read(File.expand_path("~/home.openvpn.conf"))
 => "snip valid content" 
```
